<?PHP
/**
 * glossary_add.php
 *
 * longdesc
 *
 * LICENSE: This source file is subject to version 4.0 of the Creative Commons
 * license that is available through the world-wide-web at the following URI:
 * https://creativecommons.org/licenses/by/4.0/
 *
 * @category   Geochemistry
 * @package    EarthChem Portal
 * @author     Jason Ash <jasonash@ku.edu>
 * @copyright  IEDA (http://www.iedadata.org/)
 * @license    https://creativecommons.org/licenses/by/4.0/  Creative Commons License 4.0
 * @version    GitHub: $
 * @link       http://ecp.iedadata.org
 * @see        EarthChem, Geochemistry
 */


session_start();
include("geopasstest.php");
if (isset($user)) { // Only a logged-in user can add a glossary entry 
	$users_pkey=$userpkey;
	include('db.php');
	include ('start_new_search.php'); // This will make a new record in the search_query table and give us the pkey 
	

	
	$search_query_pkey=$pkey; // make an alias for this to keep the pkeys from glossary and search_query straight
	$glossary_pkey=$db->get_var("SELECT nextval('glossary_seq') as glossary_pkey"); // get a new pkey for glossary table




	$sql="insert into glossary (pkey,users_pkey,search_query_pkey,published,glossary_name,description ) values ($glossary_pkey, $users_pkey, $search_query_pkey, 0, '', '' )"; 
	$glossary_insert=$db->query($sql);
	$getuser = $db->get_row("select * from users where pkey = $users_pkey");
	if ($getuser->EMAIL != 'eejones@ku.edu') { // Do not send email to Doug if Eileen is just testing. 
	//<CFMAIL to="jdwalker@ku.edu" from="eejones@ku.edu" subject="New EarthChem Glossary Entry" type="text">
	/*$email_msg = "A new Glossary Entry has been submitted by $getuser->FIRSTNAME $getuser->LASTNAME $getuser->EMAIL to EarthChem. It is awaiting publication.
	http://geoportal.kgs.ku.edu/earthchem/jtest/search.cfm?pkey=$search_query_pkey&glossary_pkey=$glossary_pkey
	This message was automatically generated by the EarthChem Glossary software when the Glossary Entry was added. 
	The Glossary Entry can be edited or deleted by its Author until it is published. 
	It can be edited, deleted, published or unpublished at any time by a user with User Level of admin. "; */
	}
	
	
	header("Location: search.php?pkey=$search_query_pkey&glossary_pkey=$glossary_pkey&foo=foo"); 
//<CFLOCATION url="search.cfm?pkey=#pkey#&search_query_pkey=#search_query_pkey#&glossary_pkey=#glossary_seq.glossary_pkey#" addtoken="No">
} else { // User is not logged in, so they were not allowed to add a new glossary entry 
	include('includes/ks_head.html');
	echo '
<P/>You must be logged in to add a Glossary Entry.
<P/><A href="login.php">Login
</A>
<P/><A href="index.php">New Search
</A>';
	include('includes/ks_footer.html');
}

?>